// NOTE: shoul use env file instead

export const jwtConstants = {
  secret:
    //'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
    // secret: process.env.JWT_SECRET
    'NO UTILICE ESTE VALOR. EN SU LUGAR, CREA UN SECRETO COMPLEJO Y MANTÉNGALO SEGURO FUERA DEL CÓDIGO FUENTE.',
};
